#!/bin/bash

 . /etc/default/scylla-server

EC2_META_URL=http://169.254.169.254/latest/meta-data

CPU_SET=""
if [ x"$SCYLLA_CPU_SET" != "x" ]; then
	CPU_SET="--cpuset $SCYLLA_CPU_SET"
fi

if [ "$SCYLLA_PRODUCTION" == "true" ]; then
	DEV_MODE=""
	if [ ! -f /var/lib/scylla/.io_setup_done ]; then
		DATA_DIR=`/usr/lib/scylla/scylla_config_get.py --config $SCYLLA_CONF/scylla.yaml --get data_file_directories | head -n1`
		iotune --evaluation-directory $DATA_DIR \
               --format envfile \
               --options-file /var/lib/scylla/io.conf \
               $CPU_SET \
               --timeout 600

		if [ $? -ne 0 ]; then
			echo "/var/lib/scylla did not pass validation tests, it may not be on XFS and/or has limited disk space."
			echo "This is a non-supported setup, please bind mount an XFS volume."
			exit 1
		fi
		touch /var/lib/scylla/.io_setup_done
	fi
	source /var/lib/scylla/io.conf
else
	DEV_MODE="--developer-mode true"
fi

if [ -z "$LISTEN_ADDRESS" ] ;
then
    export LISTEN_ADDRESS=$(curl -Ls -m 4 ${EC2_META_URL}/local-ipv4)
fi
echo "Local IP address is $LISTEN_ADDRESS ..."

if [ x"$SEEDS" != "x" ];then
	SEEDS=$(echo $SEEDS | tr "," "\n" | xargs getent hosts | awk '{ print $1 }' | tr "\n" "," | head -c -1)
else
	SEEDS="$LISTEN_ADDRESS"
fi

if [ "x$SUBNET_TYPE" = xinternal ];
then
    export BROADCAST_ADDRESS=$LISTEN_ADDRESS

    if [ -z $SNITCH ] ;
    then
        export SNITCH="Ec2Snitch"
    fi
else
    echo "Public deployment not supported for ScyllaDB right now"
    exit 1
fi


python -c "import sys, os; sys.stdout.write(os.path.expandvars(open('/scylladb_template.yaml').read()))" > /etc/scylla/scylla.yaml

if [ x"$SCYLLA_SMP" == "x" ];then
        SCYLLA_SMP=1
fi

if [ x"$SCYLLA_MEMORY" == "x" ];then
        SCYLLA_MEMORY="1G"
fi

/usr/bin/scylla --smp $SCYLLA_SMP \
                --memory $SCYLLA_MEMORY \
                --log-to-syslog 0 \
                --log-to-stdout 1 \
                --default-log-level info \
                --options-file /etc/scylla/scylla.yaml \
                --network-stack posix \
                $DEV_MODE \
                $SEASTAR_IO \
                $CPU_SET \
                &

source /etc/default/scylla-jmx
export SCYLLA_HOME SCYLLA_CONF
exec /usr/lib/scylla/jmx/scylla-jmx -l /usr/lib/scylla/jmx &

# not perfect, also waits for scylla-jmx only, with scylla not running
wait
